version: '3'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    #image: todolist-client
   # volumes:
    #  - ./client:/app
    ports:
      - 3000:3000
    networks:
      - todo-app-network
networks:
  todo-app-network:

